import PageWrapper from '@/components/layout/PageWrapper'

export const metadata = { title: 'Terms of Service — Maritime AI Guide' }

export default function TermsPage() {
  return (
    <PageWrapper>
      <div className="max-w-3xl mx-auto px-4 pt-28 pb-16">
        <h1 className="font-display text-4xl font-bold text-primary mb-2">Terms of Service</h1>
        <p className="text-text-muted text-sm mb-10">Last updated: June 2025</p>

        <div className="space-y-8">
          {[
            {
              title: '1. Acceptance of Terms',
              content: `By accessing or using Maritime AI Guide, you agree to be bound by these Terms of Service. If you do not agree, please do not use the platform.`
            },
            {
              title: '2. Platform Use',
              content: `Maritime AI Guide is provided for informational and educational purposes. The platform is intended to help students understand maritime career options. You agree to use the platform only for lawful purposes and in compliance with all applicable Indian laws and regulations.`
            },
            {
              title: '3. Accuracy Disclaimer',
              content: `The information on this platform is based on DGS Training Circular No. 12 of 2020 and other official government sources. However, eligibility rules, age limits, and course requirements may be updated by the Directorate General of Shipping. We strive to keep information current, but we strongly recommend verifying all details directly with the Directorate General of Shipping (www.dgshipping.gov.in) or Indian Maritime University (www.imu.edu.in) before making any enrollment decisions.`
            },
            {
              title: '4. No Admission Guarantee',
              content: `Maritime AI Guide does not guarantee admission to any maritime institution or course. Eligibility checks on our platform are indicative only. Final eligibility is determined by the respective institutions and the Directorate General of Shipping.`
            },
            {
              title: '5. AI Advisor (NavAI) Disclaimer',
              content: `NavAI responses are generated by AI and may contain errors. NavAI is not a substitute for official government guidance or professional maritime career counseling. Always verify AI-generated information with official sources.`
            },
            {
              title: '6. User Accounts',
              content: `You are responsible for maintaining the confidentiality of your account credentials. You agree to notify us immediately of any unauthorized use of your account. We reserve the right to terminate accounts that violate these terms.`
            },
            {
              title: '7. Intellectual Property',
              content: `All content on Maritime AI Guide, including text, graphics, logos, and AI-generated content, is the property of Maritime AI Guide and protected by applicable intellectual property laws.`
            },
            {
              title: '8. Limitation of Liability',
              content: `Maritime AI Guide shall not be liable for any indirect, incidental, or consequential damages arising from the use of or inability to use the platform. Our total liability shall not exceed the amount paid by you for any premium services.`
            },
            {
              title: '9. Changes to Terms',
              content: `We reserve the right to modify these terms at any time. Continued use of the platform after changes constitutes acceptance of the new terms.`
            },
            {
              title: '10. Contact',
              content: `For questions about these Terms, contact us at legal@maritimeaiguide.in.`
            },
          ].map((section) => (
            <div key={section.title}>
              <h2 className="font-display text-xl font-semibold text-primary mb-3">{section.title}</h2>
              <p className="text-text-secondary leading-relaxed">{section.content}</p>
            </div>
          ))}
        </div>
      </div>
    </PageWrapper>
  )
}
