CREATE TYPE gender_type AS ENUM ('male', 'female', 'other', 'prefer_not_to_say');
CREATE TYPE category_type AS ENUM ('general', 'sc', 'st', 'obc_ncl', 'ews');
CREATE TYPE qualification_type AS ENUM ('class_10', 'class_11', 'class_12', 'diploma', 'engineering_grad', 'bsc_grad', 'other_grad');
CREATE TYPE user_role_type AS ENUM ('student', 'admin', 'super_admin', 'college_partner', 'company_partner');
CREATE TYPE department_type AS ENUM ('deck', 'engine', 'eto', 'ratings', 'catering');
CREATE TYPE dgs_status_type AS ENUM ('approved', 'pending', 'suspended', 'not_listed', 'flagged');
CREATE TYPE college_type AS ENUM ('imu_campus', 'imu_affiliated', 'dgs_approved_private', 'unverified');
CREATE TYPE sponsorship_type AS ENUM ('full', 'partial', 'guaranteed_employment');
CREATE TYPE ai_intent_type AS ENUM ('factual_lookup', 'eligibility_query', 'conversational', 'out_of_scope');
CREATE TYPE session_type AS ENUM ('navai_chat', 'eligibility', 'roadmap');
CREATE TYPE event_category_type AS ENUM ('navigation', 'interaction', 'conversion', 'error', 'ai', 'search');
CREATE TYPE language_type AS ENUM ('en', 'hi');
CREATE TYPE priority_type AS ENUM ('fastest', 'highest_salary', 'lowest_cost', 'work_life_balance');
CREATE TYPE target_dept_type AS ENUM ('deck', 'engine', 'eto', 'ratings', 'undecided');
CREATE TYPE admission_type AS ENUM ('cet_only', 'own_exam', 'both', 'direct');
CREATE TYPE cet_status_type AS ENUM ('upcoming', 'registration_open', 'exam_completed', 'results_declared');
CREATE TYPE difficulty_type AS ENUM ('easy', 'medium', 'hard');
CREATE TYPE subject_type AS ENUM ('mathematics', 'physics', 'chemistry', 'english', 'general_aptitude');
CREATE TYPE confidence_type AS ENUM ('high', 'medium', 'low', 'needs_verification');
CREATE TYPE fraud_type AS ENUM ('not_dgs_approved', 'fee_fraud', 'fake_placement', 'other');
CREATE TYPE report_status_type AS ENUM ('pending', 'investigating', 'verified', 'dismissed');
CREATE TYPE application_status_type AS ENUM ('applied', 'written_test', 'medical', 'interview', 'offered', 'rejected', 'withdrawn');
CREATE TYPE partner_tier_type AS ENUM ('basic', 'standard', 'premium');
CREATE TYPE company_type AS ENUM ('indian', 'international', 'ship_management', 'offshore');
CREATE TYPE digest_type AS ENUM ('daily', 'weekly', 'never');
CREATE TYPE notification_type AS ENUM ('cet_reminder', 'eligibility_update', 'sponsorship_open', 'system', 'fraud_alert');
CREATE TYPE announcement_type AS ENUM ('cet_update', 'new_circular', 'sponsorship_open', 'platform_update');
CREATE TYPE audience_type AS ENUM ('all', 'premium', 'deck_aspirants', 'engine_aspirants');
CREATE TYPE english_check_type AS ENUM ('class_10', 'class_12', 'either', 'degree', 'diploma_or_degree');
CREATE TYPE eligibility_qualification_type AS ENUM ('class_10', 'class_12_pcm', 'diploma', 'bsc', 'be_btech', 'other');
CREATE TYPE device_type AS ENUM ('mobile', 'tablet', 'desktop');
CREATE TYPE message_role_type AS ENUM ('user', 'assistant', 'system');
CREATE TYPE program_status_type AS ENUM ('open', 'closed', 'opening_soon');
